name: Postman Test

on: push

jobs:
  build:
    runs-on: postman/newman:latset
 
    
 
    steps:
    - name: Install Newman
      run: npm install -g newman
    - name: Run the Postman tests
      run: newman run "collection.json"
